### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by ericandrewlewis** [aamaliaa/mta#1]
Hi! 

I tried using the example code to fetch arrival times at Christopher St. station with this code:

```
var Mta = require('./');
var mta = new Mta({
  key: '{{my key here}}', // only needed for mta.schedule() method
  feed_id: 1                  // optional, default = 1
});

mta.schedule(133, function (err, result) {
  console.log( err, result );
});
```

This produces

```
> $ node example.js
[TypeError: Cannot read property 'build' of null] undefined
```

I notice if I remove [this line](https://github.com/aamaliaa/mta/blob/1aa3b9349db50531e30270283d0286a14bc2a6b9/lib/parsers/gtfs.js#L11), it works. The file `lib/data/proto/nyct-subway.proto` is included in the project, so I wonder if the reference to `node_modules/mta-gtfs` is an artifact?

Love the package btw! :smile:

**Comment by ericandrewlewis** [comment]
Ah — okay.

The `node_modules/mta-gtfs` bit is there so that the mta module can be used by another node project.

I think we could use `__dirname` here, which will give the absolute folder path of the script being executed, rather than expecting the package to be used as a module, therefore inside of the `node_modules/mta-gtfs` folder.

```javascript
var file = path.resolve( __dirname + '/../data/proto/nyct-subway.proto' );
```

**Comment by aamaliaa** [comment]
Fixed! Thanks @ericandrewlewis for finding this!
